<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_program-fields',
		'title' => 'Program Fields',
		'fields' => array (
			array (
				'key' => 'field_5a907505aed60',
				'label' => 'Department Website',
				'name' => 'department_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'https://uri.edu/department',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a90756aaed61',
				'label' => 'Catalog Info',
				'name' => 'catalog_info',
				'type' => 'text',
				'instructions' => 'Enter the URL of the corresponding catalog page.',
				'default_value' => '',
				'placeholder' => 'https://web.uri.edu/catalog/music/',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a9076e700469',
				'label' => 'Course Descriptions',
				'name' => 'course_descriptions',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a907649020b1',
				'label' => 'Admission Info',
				'name' => 'admission_info',
				'type' => 'text',
				'instructions' => 'URL to admission information',
				'default_value' => 'https://uri.edu/admission',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a907670020b2',
				'label' => 'Apply',
				'name' => 'apply',
				'type' => 'select',
				'choices' => array (
					'undergraduate' => 'Undergraduate',
					'graduate' => 'Graduate',
				),
				'default_value' => 'undergraduate',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a9077420046a',
				'label' => 'Course Schedule',
				'name' => 'course_schedule',
				'type' => 'text',
				'instructions' => 'I\'m sorry.',
				'default_value' => 'https://uri.edu/course-schedule',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a9078363b98f',
				'label' => 'Time to Completion',
				'name' => 'time_to_completion',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5a90787f3b990',
				'label' => 'Application Deadline',
				'name' => 'application_deadline',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'program',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
